### ISSUE TITLE
syncrepl: expected bytes failure in UUID init

### ISSUE THREAD

**Issue by MartinBasti** [pyldap/pyldap#103]
Hello, I'm getting following traceback from syncrepl module:

```
Traceback (most recent call last):
  File "/usr/libexec/ipa/ipa-dnskeysyncd", line 114, in <module>
    while ldap_connection.syncrepl_poll(all=1, msgid=ldap_search):
  File "/usr/lib64/python3.5/site-packages/ldap/syncrepl.py", line 352, in syncrepl_poll
    add_intermediates=1, add_ctrls=1, all = 0
  File "/usr/lib64/python3.5/site-packages/ldap/ldapobject.py", line 702, in result4 
    resp_data = [ (t,r,DecodeControlTuples(c,resp_ctrl_classes)) for t,r,c in resp_data ]
  File "/usr/lib64/python3.5/site-packages/ldap/ldapobject.py", line 702, in <listcomp>
    resp_data = [ (t,r,DecodeControlTuples(c,resp_ctrl_classes)) for t,r,c in resp_data ]
  File "/usr/lib64/python3.5/site-packages/ldap/controls/__init__.py", line 147, in DecodeControlTuples
    control.decodeControlValue(encodedControlValue)
  File "/usr/lib64/python3.5/site-packages/ldap/syncrepl.py", line 135, in decodeControlValue
    uuid = UUID(bytes=d[0].getComponentByName('entryUUID'))
  File "/usr/lib64/python3.5/uuid.py", line 150, in __init__
    assert isinstance(bytes, bytes_), repr(bytes)
AssertionError: syncUUID(hexValue='cbf9700f569f11e79090c09ce2d35280')
```

Version: `python3-pyldap-2.4.35.1-1.fc25.x86_64`

**Comment by akkornel** [comment]
Hello!

You've come across a bug that I hit as well.  I've got #99 open to address it.

In fact, if you could take the commit from that PR, and test it, and add your test results to the PR, that would be great!

**Comment by MartinBasti** [comment]
Hello, thank you for info, that PR works for me.

**Comment by rbarrois** [comment]
Hi!

We've just merged the fixed PR; I'm closing this issue since it will be solved in the next pyldap release.
