### ISSUE TITLE
Segfault on in ldap_sasl_interaction

### ISSUE THREAD

**Issue by msimacek** [pyldap/pyldap#16]
`Modules/LDAPObject.c:interaction` can segfault due to missing error checking of return value of `PyBytes_AsString` (as noted in a comment next to it).

```
#0  0x00007ffff6ce274a in strlen () from /lib64/libc.so.6
#1  0x00007ffff6ce247e in strdup () from /lib64/libc.so.6
#2  0x00007fffe7ca69d3 in interaction (flags=4294935448, SASLObject=<external(mech='EXTERNAL', cb_value_dict={16385: 'root'}) at remote 0x7fffe1be8518>, interact=0x55555639b2b0) at Modules/LDAPObject.c:579
#3  py_ldap_sasl_interaction (ld=ld@entry=0x555556370190, flags=flags@entry=2, defaults=defaults@entry=0x7fffe1be8518, in=<optimized out>) at Modules/LDAPObject.c:613
#4  0x00007fffe7a63895 in ldap_int_sasl_bind (ld=ld@entry=0x555556370190, dn=dn@entry=0x7ffff7fcf878 "", mechs=mechs@entry=0x555555cfebc0 "EXTERNAL GSS-SPNEGO GSSAPI DIGEST-MD5 CRAM-MD5 ANONYMOUS", sctrls=sctrls@entry=0x0, cctrls=cctrls@entry=0x0, flags=flags@entry=2, 
    interact=0x7fffe7ca69a0 <py_ldap_sasl_interaction>, defaults=0x7fffe1be8518, result=0x0, rmech=0x7fffffff85b8, msgid=0x7fffffff85b4) at cyrus.c:547
#5  0x00007fffe7a66de8 in ldap_sasl_interactive_bind (ld=ld@entry=0x555556370190, dn=dn@entry=0x7ffff7fcf878 "", mechs=0x555555cfebc0 "EXTERNAL GSS-SPNEGO GSSAPI DIGEST-MD5 CRAM-MD5 ANONYMOUS", mechs@entry=0x0, serverControls=serverControls@entry=0x0, 
    clientControls=clientControls@entry=0x0, flags=flags@entry=2, interact=0x7fffe7ca69a0 <py_ldap_sasl_interaction>, defaults=0x7fffe1be8518, result=0x0, rmech=0x7fffffff85b8, msgid=0x7fffffff85b4) at sasl.c:471
#6  0x00007fffe7a6700e in ldap_sasl_interactive_bind_s (ld=0x555556370190, dn=0x7ffff7fcf878 "", mechs=mechs@entry=0x0, serverControls=0x0, clientControls=0x0, flags=2, interact=0x7fffe7ca69a0 <py_ldap_sasl_interaction>, defaults=0x7fffe1be8518) at sasl.c:505
#7  0x00007fffe7ca7e18 in l_ldap_sasl_interactive_bind_s (self=0x7fffe23ab788, args=<optimized out>) at Modules/LDAPObject.c:728
#8  0x00007ffff7a61b9d in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7fffffff8738, func=<built-in method sasl_interactive_bind_s of LDAP object at remote 0x7fffe23ab788>) at /usr/src/debug/Python-3.4.3/Python/ceval.c:4587
#9  PyEval_EvalFrameEx (
    f=f@entry=Frame 0x5555563ee108, for file /usr/lib64/python3.4/site-packages/pyldap-2.4.21-py3.4-linux-x86_64.egg/ldap/ldapobject.py, line 244, in _ldap_call (self=<SimpleLDAPObject(bytes_mode=None, bytes_mode_hardfail=True, _trace_level=0, _trace_file=<_io.TextIOWrapper at remote 0x7ffff7f79630>, _l=<LDAP at remote 0x7fffe23ab788>, _trace_stack_limit=None, _uri='ldapi://%2fvar%2frun%2fslapd-EXAMPLE-COM.socket', timeout=-1, _ldap_object_lock=<LDAPLock(_desc='opcall within <ldap.ldapobject.SimpleLDAPObject object at 0x7fffe1be8470>', _lock=<DummyLock at remote 0x7fffe1be84e0>) at remote 0x7fffe1be84a8>) at remote 0x7fffe1be8470>, func=<built-in method sasl_interactive_bind_s of LDAP object at remote 0x7fffe23ab788>, args=('', <external(mech='EXTERNAL', cb_value_dict={16385: 'root'}) at remote 0x7fffe1be8518>, None, None, 2), kwargs={}, diagnostic_message_success=None), throwflag=throwflag@entry=0) at /usr/src/debug/Python-3.4.3/Python/ceval.c:2902
#10 0x00007ffff7a63636 in PyEval_EvalCodeEx (_co=_co@entry=<code at remote 0x7fffe5f22420>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=7, kws=0x7fffe2082a28, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at /usr/src/debug/Python-3.4.3/Python/ceval.c:3617
```

**Comment by encukou** [comment]
Should be fixed by https://github.com/pyldap/pyldap/pull/23
