### ISSUE TITLE
simple_bind_s() breaks when unicode is passed to "cred"

### ISSUE THREAD

**Issue by ethankleinman** [pyldap/pyldap#39]
When I try to passing unicode like 

> asdf°asdfasdfasdfƟƯa

 for the credentials in `simple_bind_s()`, I get a unicode error. I am using py2.

```
def simple_bind_s(self,who='',cred='',serverctrls=None,clientctrls=None):
    """
    simple_bind_s([who='' [,cred='']]) -> 4-tuple
    """
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
    return resp_type, resp_data, resp_msgid, resp_ctrls
```

**Comment by rbarrois** [comment]
I guess it shouldn't.

Could you provide more details?
Typically:
- What `bytes_mode` did you use?
- What error message did you get?

Thanks!

**Comment by ethankleinman** [comment]
Hi @rbarrois! 
I have `bytes_mode=False`
And the error message is:

> UnicodeEncodeError at /my/test
> 'ascii' codec can't encode character u'\xb0' in position 4: ordinal not in range(128)

Variables I am passing it:
`who: cn=someuser,ou=Acitve,ou=Users,o=Organization`
`cred: asdf°asdfasdfasdfƟƯa`

Both variables are unicode type. If I pass a unicode string that is within the ascii range it seems to work fine; `cred: asdf` with the same settings throws no errors. 

Thanks!

**Comment by MrEbbinghaus** [comment]
Hey,
same here! I'm lucky (more or less) that my name contains a special character ('ö') or I have found it in production... 

```
search_s('ou=<private>,DC=private,DC=example,DC=org', 2, '(sAMAccountName=%(user)s)') returned 1 objects: cn=ebbinghaus\\, bj\xc3\xb6rn (<private>),ou=<private>,dc=private,dc=example,dc=org
Caught Exception while authenticating <private>
Traceback (most recent call last):
  File "<path to venv>/lib/python3.4/site-packages/django_auth_ldap/backend.py", line 337, in authenticate
    self._authenticate_user_dn(password)
  File "<path to venv>/lib/python3.4/site-packages/django_auth_ldap/backend.py", line 453, in _authenticate_user_dn
     self._bind_as(self.dn, password, sticky=sticky)
  File "<path to venv>/lib/python3.4/site-packages/django_auth_ldap/backend.py", line 730, in _bind_as
    force_str(bind_password))
  File "<path to venv>/lib/python3.4/site-packages/ldap/ldapobject.py", line 382, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "<path to venv>/lib/python3.4/site-packages/ldap/ldapobject.py", line 376, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "<path to venv>/lib/python3.4/site-packages/ldap/ldapobject.py", line 263, in _ldap_call
    result = func(*args,**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 18: ordinal not in range(128)
```

**Comment by maennel** [comment]
Same here. Note that the call comes from django_auth_ldap as well: 

```
  [...]
  File "build/bdist.linux-x86_64/egg/django_auth_ldap/backend.py", line 167, in authenticate
    user = ldap_user.authenticate(password)
  File "build/bdist.linux-x86_64/egg/django_auth_ldap/backend.py", line 337, in authenticate
    self._authenticate_user_dn(password)
  File "build/bdist.linux-x86_64/egg/django_auth_ldap/backend.py", line 453, in _authenticate_user_dn
    self._bind_as(self.dn, password, sticky=sticky)
  File "build/bdist.linux-x86_64/egg/django_auth_ldap/backend.py", line 730, in _bind_as
    force_str(bind_password))
  File "/lib/python2.7/site-packages/pyldap-2.4.21-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 363, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/lib/python2.7/site-packages/pyldap-2.4.21-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 357, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/lib/python2.7/site-packages/pyldap-2.4.21-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 244, in _ldap_call
    result = func(*args,**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 12: ordinal not in range(128)
```

**Comment by maennel** [comment]
This seems to be the same problem as in #54.

**Comment by stardust85** [comment]
Same problem at my side. Tried both bytes_mode=True and bytest_mode=False (changed inputs appropriately).

Python version CPython 2.7.5 on Oracle Linux 7.3
