### ISSUE TITLE
AssertionError: Should return text, got bytes instead

### ISSUE THREAD

**Issue by DMW007** [pyldap/pyldap#97]
### Environment and problem

I just installed the latest Sentry 8.17.0 using their official docker image. These sentry instance should be configured to use ApacheDs as LDAP backend for user authentication and management. For this purpose, `django-auth-ldap` was installed as [authentication backend for django](https://pythonhosted.org/django-auth-ldap/install.html). I already got this working in the past with Active Directory, so it was no big issue to customize the configuration, so that it fits to an open LDAP directory server like ApacheDs is. 

But I ran into a big problem: I got the exception `AssertionError: Should return text, got bytes instead ('mail=user@example.com,ou=administratrators,ou=sub-users,ou=users,DC=myldap,DC=example,DC=com')` when I try to login using a LDAP user. This error seems strange for me: It contains the DN of my user (I tried to login with `user@example.com` here), so the LDAP connection is working, cause the DN was fetched from the server. The second surprising thing: Python says, that text was expected, but bytes were there. And the exception message contains the DN as a string?

I took a look at the source code file https://github.com/pyldap/pyldap/blob/master/Lib/ldap/ldapobject.py line 190:

```
if value is None:
      return value

    assert isinstance(value, text_type), "Should return text, got bytes instead (%r)" % (value,)
    if not self.bytes_mode:
      return value
    else:
      return value.encode('utf-8')

```

Python checks, if `value` is not a text type, then throw a error, which seems to stop the execution. This let my login fail and result in an internal server error. 

### Workaround 

We can define the distinguished name with a placeholder:

`AUTH_LDAP_USER_DN_TEMPLATE = 'mail=%(user)s,,ou=administratrators,ou=sub-users,ou=users,DC=myldap,DC=example,DC=com'`

In this case, we avoid the error: Since the DN can be generated, there is no need for the python lib to fetch it using a LDAP request. The problem is the lack of flexibility: You can't easily have the users spread across different OUs. And it's not possible to let them choose between different attributes as username (like username or email) for login. 

For this reason, I'm searching for a long term solution, that fixes this issue and let me drop the hard coded user DN. Being not a python developer, it's not exactly clear for me, where the root issue came from: Is there something wrong with the LDAP library? Or the django provider?

### Installed versions
django-auth-ldap (1.2.12)
pyldap (2.4.35.1)
python-ldap (2.4.39)

### UPDATE: Bug and (possible) solution

I simply tried to disable the `isinstance` line by commenting it out in `/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py`. After some incorporation, it seems to be an character set issue: Our input seems not well encoded in unicode, which is checked by text_type:

```
PY2 = bool(sys.version_info[0] <= 2)
if PY2:
  text_type = unicode
else:
  text_type = str
```

So this is a custom implementation of the [six library](https://pythonhosted.org/six/), which is designed to care about compatibility issues for python 2 and 3. The `decode` method provides a [way for converting a string to utf8](https://stackoverflow.com/a/19230566/3276634), with the ability to replace non utf8 characters. When we use this method first, the check wouldn't fail and LDAP without hard coded DN is working well. 

In the moment I'm using this workaround as custom modification, but also shared it in a pull request: https://github.com/pyldap/pyldap/pull/98 Would be nice to have this in one of the next releases, so that I can drop my custom modification. 

### Full stacktrace of the error:
```
Traceback (most recent call last):
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
sentry_1                |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
sentry_1                |     return self.dispatch(request, *args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
sentry_1                |     return bound_func(*args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
sentry_1                |     response = view_func(request, *args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
sentry_1                |     return func(self, *args2, **kwargs2)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 187, in dispatch
sentry_1                |     return self.handle(request, *args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/decorators/cache.py", line 52, in _wrapped_view_func
sentry_1                |     response = view_func(request, *args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 371, in inner
sentry_1                |     return func(*args, **kwargs)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 133, in handle
sentry_1                |     response = self.handle_basic_auth(request, organization)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 67, in handle_basic_auth
sentry_1                |     elif login_form.is_valid():
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 129, in is_valid
sentry_1                |     return self.is_bound and not bool(self.errors)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 121, in errors
sentry_1                |     self.full_clean()
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 274, in full_clean
sentry_1                |     self._clean_form()
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 300, in _clean_form
sentry_1                |     self.cleaned_data = self.clean()
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/web/forms/accounts.py", line 139, in clean
sentry_1                |     password=password)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/sentry/../django/contrib/auth/__init__.py", line 49, in authenticate
sentry_1                |     user = backend.authenticate(**credentials)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 167, in authenticate
sentry_1                |     user = ldap_user.authenticate(password)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 337, in authenticate
sentry_1                |     self._authenticate_user_dn(password)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 447, in _authenticate_user_dn
sentry_1                |     if self.dn is None:
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 411, in _get_user_dn
sentry_1                |     self._load_user_dn()
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 474, in _load_user_dn
sentry_1                |     self._search_for_user_dn()
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 494, in _search_for_user_dn
sentry_1                |     results = search.execute(self.connection, {'user': self._username})
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/config.py", line 162, in execute
sentry_1                |     force_str(filterstr))
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 773, in search_s
sentry_1                |     return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 767, in search_ext_s
sentry_1                |     return self.result(msgid,all=1,timeout=timeout)[1]
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 674, in result
sentry_1                |     resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 678, in result2
sentry_1                |     resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 685, in result3
sentry_1                |     resp_ctrl_classes=resp_ctrl_classes
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 705, in result4
sentry_1                |     resp_data = self._bytesify_results(resp_data, with_ctrls=add_ctrls)
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 237, in _bytesify_results
sentry_1                |     for (dn, fields) in results
sentry_1                |   File "/usr/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 190, in _bytesify_value
sentry_1                |     assert isinstance(value, text_type), "Should return text, got bytes instead (%r)" % (value,)
sentry_1                | AssertionError: Should return text, got bytes instead ('mail=user@example.com,ou=administratrators,ou=sub-users,ou=users,DC=myldap,DC=example,DC=com')
sentry_1                | 13:04:54 [ERROR] django.request: Internal Server Error: /auth/login/sentry/ (status_code=500 request=<WSGIRequest
sentry_1                | path:/auth/login/sentry/,

```

**Comment by encukou** [comment]
Please check if this still happens with python-ldap 3.0.0b1, which you can install by:

    pip uninstall pyldap
    pip install --pre --upgrade python-ldap

and report any issues to [the python-ldap tracker](https://github.com/python-ldap/python-ldap/issues).
